### ISSUE TITLE
The status of the extension

### ISSUE THREAD

**Issue by bkavlak** [stac-extensions/virtual-assets#1]
Hey people,

What do you think about pushing the extension to pilot?

We want to use it to describe the below scenario:

We have a scene that is tiled. It means that one image is clipped into multiple tiles. However, the metadata for all of the images is the same. We want to build an STAC Item for the scene and add tiles into virtual:assets to merge them later. For example:

Here is the structure of the scene:
```
scene_name_r1c1.tif
scene_name_r1c2.tif
scene_name_r2c1.tif
scene_name_r2c2.tif
metadata.xml
```

We want to use virtual assets to define:
```
"assets": {
    "metadata": {"href": "metadata.xml", "type": "application/xml"}
}
"virtual:assets": {
    "scene": {
        title: "some_title",
        hrefs: [
            "scene_name_r1c1.tif",
            "scene_name_r1c2.tif",
            "scene_name_r2c1.tif",
            "scene_name_r2c2.tif"
        ],
        type: "image/tiff"
    }
}
```

**Comment by bkavlak** [comment]
I tried to adapt Pystac for this extension and realized it's a fundamental change rather than an extension. I'll probably use it under the `properties` field as an extension.

**Comment by emmanuelmathot** [comment]
Hello @bkavlak. Thank you for your interest and sorry for the late reply.
Indeed, the extension is not trivial and I wanted more feedback on the main object `virtual:assets`. Maybe another approach with a role in `assets` would be easier to include and specific extension. Something like:

```json
"assets": {
    "metadata": {"href": "metadata.xml", "type": "application/xml"}
    "B04":  {"href": "b04.tif", "type": "image/tiff"}
    "B05":  {"href": "b05.tif", "type": "image/tiff"}
    "ndvi": {
        "roles": ["virtual"]
        "virtual:assets_href": [ "#B04", "#B05" ],
        "title": "Normalized Difference Vegetation Index",
        "type": "image/tiff"
    }
}
```

I plan to release it at the STAC sprint #8 next week.

**Comment by bkavlak** [comment]
@emmanuelmathot Thanks for the update!

I was thinking of switching to the same idea. With the current setup, an asset extension, as you describe, seems a better fit.

I cannot join the sprint, but I would love to support this extension idea. This is very useful since premium data providers have different abstract concepts in their metadata (e.g., tiling the images into other files but having the same metadata for tiles in the same scene), and some processing is required to transform them to the common formats we are used to.

**Comment by bkavlak** [comment]
To add a feedback:

We used the extension (without validating) in our application before applying a merge. We remove the role and `vrt:hrefs` afterward, which makes it a smooth transition to the `real` asset.

Thanks a lot for the work here!
