### ISSUE TITLE
media type for virtual-assets

### ISSUE THREAD

**Issue by vincentsarago** [stac-extensions/virtual-assets#3]
IMO it would be nice to quickly be able to filter virtual-assets in set of assets by using a specific media type or maybe an additional entry `virtual: True` 🤷

**Comment by bkavlak** [comment]
the media type is usually used for mime types, `virtual` as a role looked better to me

https://github.com/stac-extensions/virtual-assets#mandatory-role:~:text=B02%22%20%7D%0A%5D-,Mandatory%20role,-Every%20asset%20defined

**Comment by emmanuelmathot** [comment]
The `virtual` role indicates when an asset is virtual
